services:
  backend:
    build:
      context: ./backend
    container_name: extraalearn-backend
    ports:
      - "7860:7860"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: extraalearn-frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    restart: unless-stopped
